---
- name: Add keys to hosts
  hosts: all
  tasks:
  - name: Install Key
    authorized_key:
     user: USERNAME
     state: present
     key: "{{ lookup('file', '/home/USERNAME/.ssh/id_rsa.pub') }}"
