---
- hosts: localhost
  become: yes
  vars:
    nfsmounts:
      - {  path: "/mnt/nfs_mount", src: "10.10.10.10:/mnt/share1" }
      - {  path: "/mnt/nfs_mount_2", src: "10.10.10.10:/mnt/share2" }
  tasks:
      - name: mount the nfsshare in client side
        mount:
          fstype: nfs
          opts: hard,bg
          dump: 0
          passno: 0
          state: mounted
          src: "{{item.src}}"
          path: "{{item.path}}"
        with_items: "{{nfsmounts}}"
