---
- hosts: dev
  become: yes

  pre_tasks:

   - name: Remove old lynis dir.
     file:
       path: /opt/lynis
       state: absent

  tasks:

   - name: Download file with check (sha256).
     get_url:
       url: https://downloads.cisofy.com/lynis/lynis-3.0.1.tar.gz
       dest: /opt/
       checksum: sha256:8381b62e11a5e0ead417bcfd92845adab7dc3b9d06271c852a1166cb65a61aff
       validate_certs: yes

   - name: Extract lynis.
     unarchive:
       src: /opt/lynis-3.0.1.tar.gz
       dest: /opt/
       remote_src: yes

   - name: Remove lynis tar.
     file:
       path: /opt/lynis-3.0.1.tar.gz
       state: absent

   - name: Run scan and output to file.
     shell: ./lynis audit system > /tmp/"$(hostname -s)_$(date +%d-%m-%Y).report"
     args:
      chdir: /opt/lynis/

   - name: Find the report.
     find:
       paths: "/tmp/"
       recurse: no
       patterns: "*.report"
     register: report

   - name: Copy report to primary.
     fetch:
       src: "{{ item.path }}"
       dest: ./scans/
       flat: yes
     with_items: "{{ report.files }}"

   - name: Find report file.
     find:
       paths: /tmp/
       patterns: "*.report"
     register: report_to_delete

   - name: Delete report.
     file:
       path: "{{ item.path }}"
       state: absent
     with_items: "{{ report_to_delete.files }}"

   - name: Remove lynis folder from opt.
     file:
       path: /opt/lynis
       state: absent
